// Code generated by MockGen. DO NOT EDIT.
// Source: config.go
//
// Generated by this command:
//
//	mockgen -package mock -source=config.go -destination=mock/config.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
	isgomock struct{}
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// ConcurrentSize mocks base method.
func (m *MockConfig) ConcurrentSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConcurrentSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// ConcurrentSize indicates an expected call of ConcurrentSize.
func (mr *MockConfigMockRecorder) ConcurrentSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcurrentSize", reflect.TypeOf((*MockConfig)(nil).ConcurrentSize))
}

// MaxConcurrentSize mocks base method.
func (m *MockConfig) MaxConcurrentSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxConcurrentSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// MaxConcurrentSize indicates an expected call of MaxConcurrentSize.
func (mr *MockConfigMockRecorder) MaxConcurrentSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxConcurrentSize", reflect.TypeOf((*MockConfig)(nil).MaxConcurrentSize))
}

// ReadTimeout mocks base method.
func (m *MockConfig) ReadTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ReadTimeout indicates an expected call of ReadTimeout.
func (mr *MockConfigMockRecorder) ReadTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTimeout", reflect.TypeOf((*MockConfig)(nil).ReadTimeout))
}
