// Code generated by MockGen. DO NOT EDIT.
// Source: msg.go
//
// Generated by this command:
//
//	mockgen -package mock -source=msg.go -destination=mock/msg.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	mq "github.com/FrogoAI/mq-balancer/subscriber/mq"
	gomock "go.uber.org/mock/gomock"
)

// MockMsg is a mock of Msg interface.
type MockMsg struct {
	ctrl     *gomock.Controller
	recorder *MockMsgMockRecorder
	isgomock struct{}
}

// MockMsgMockRecorder is the mock recorder for MockMsg.
type MockMsgMockRecorder struct {
	mock *MockMsg
}

// NewMockMsg creates a new mock instance.
func NewMockMsg(ctrl *gomock.Controller) *MockMsg {
	mock := &MockMsg{ctrl: ctrl}
	mock.recorder = &MockMsgMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMsg) EXPECT() *MockMsgMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockMsg) Copy(subject string) mq.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", subject)
	ret0, _ := ret[0].(mq.Msg)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockMsgMockRecorder) Copy(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockMsg)(nil).Copy), subject)
}

// Data mocks base method.
func (m *MockMsg) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockMsgMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockMsg)(nil).Data))
}

// Header mocks base method.
func (m *MockMsg) Header() map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockMsgMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMsg)(nil).Header))
}

// IsReply mocks base method.
func (m *MockMsg) IsReply() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReply")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReply indicates an expected call of IsReply.
func (mr *MockMsgMockRecorder) IsReply() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReply", reflect.TypeOf((*MockMsg)(nil).IsReply))
}

// ReplyTo mocks base method.
func (m *MockMsg) ReplyTo() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplyTo")
	ret0, _ := ret[0].(string)
	return ret0
}

// ReplyTo indicates an expected call of ReplyTo.
func (mr *MockMsgMockRecorder) ReplyTo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyTo", reflect.TypeOf((*MockMsg)(nil).ReplyTo))
}

// Respond mocks base method.
func (m *MockMsg) Respond(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Respond", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Respond indicates an expected call of Respond.
func (mr *MockMsgMockRecorder) Respond(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Respond", reflect.TypeOf((*MockMsg)(nil).Respond), arg0)
}

// RespondMsg mocks base method.
func (m *MockMsg) RespondMsg(arg0 mq.Msg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondMsg indicates an expected call of RespondMsg.
func (mr *MockMsgMockRecorder) RespondMsg(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondMsg", reflect.TypeOf((*MockMsg)(nil).RespondMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMsg) SetHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeader", key, value)
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMsgMockRecorder) SetHeader(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMsg)(nil).SetHeader), key, value)
}

// Subject mocks base method.
func (m *MockMsg) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockMsgMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockMsg)(nil).Subject))
}
