name: Go

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.9.0
          golangci-lint run -v ./...

  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Unit tests
        run: GOMAXPROCS=$(nproc) go test -race -p $(nproc) -parallel=$(nproc) ./...

  integration-test:
    name: integration test
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:latest
        ports:
          - 4222:4222
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Integration tests
        run: GOMAXPROCS=$(nproc) go test -race -tags="integration" -run="TestIntegration" -p $(nproc) -parallel=$(nproc) ./...

  coverage:
    name: coverage
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:latest
        ports:
          - 4222:4222
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          go install github.com/boumenot/gocover-cobertura@latest
          go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Tests with coverage
        run: |
          GOMAXPROCS=$(nproc) go test -coverprofile=coverage.out -cover -race -tags="integration" -p $(nproc) -parallel=$(nproc) ./...
          go-test-coverage --config=./.testcoverage.yml
          gocover-cobertura < coverage.out > coverage.xml
      - name: Bench
        run: go test -bench=. -run="^$$" ./...
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
